-- RUN THIS SCRIPT THIRD

UPDATE locations SET city = UPPER(city);

UPDATE locations SET country_name = 'UNITED STATES' WHERE country_abbreviation = 'US';
UPDATE locations SET country_name = 'MEXICO' WHERE country_abbreviation = 'MX';
UPDATE locations SET country_name = 'CANADA' WHERE country_abbreviation = 'CA';
UPDATE locations SET country_name = 'GERMANY' WHERE country_abbreviation = 'DE';
UPDATE locations SET country_name = 'FRANCE' WHERE country_abbreviation = 'FR';
UPDATE locations SET country_name = 'ITALY' WHERE country_abbreviation = 'IT';
UPDATE locations SET country_name = 'SPAIN' WHERE country_abbreviation = 'ES';


UPDATE locations SET state_name = 'ALABAMA' WHERE state_abbreviation = 'AL';
UPDATE locations SET state_name = 'ALASKA' WHERE state_abbreviation = 'AK';
UPDATE locations SET state_name = 'ARIZONA' WHERE state_abbreviation = 'AZ';
UPDATE locations SET state_name = 'ARKANSAS' WHERE state_abbreviation = 'AR';
UPDATE locations SET state_name = 'CALIFORNIA' WHERE state_abbreviation = 'CA';
UPDATE locations SET state_name = 'COLORADO' WHERE state_abbreviation = 'CO';
UPDATE locations SET state_name = 'CONNECTICUT' WHERE state_abbreviation = 'CT';
UPDATE locations SET state_name = 'DELAWARE' WHERE state_abbreviation = 'DE';
UPDATE locations SET state_name = 'FLORIDA' WHERE state_abbreviation = 'FL';
UPDATE locations SET state_name = 'GEORGIA' WHERE state_abbreviation = 'GA';
UPDATE locations SET state_name = 'HAWAII' WHERE state_abbreviation = 'HI';
UPDATE locations SET state_name = 'IDAHO' WHERE state_abbreviation = 'ID';
UPDATE locations SET state_name = 'ILLINOIS' WHERE state_abbreviation = 'IL';
UPDATE locations SET state_name = 'INDIANA' WHERE state_abbreviation = 'IN';
UPDATE locations SET state_name = 'IOWA' WHERE state_abbreviation = 'IA';
UPDATE locations SET state_name = 'KANSAS' WHERE state_abbreviation = 'KS';
UPDATE locations SET state_name = 'KENTUCKY' WHERE state_abbreviation = 'KY';
UPDATE locations SET state_name = 'LOUISIANA' WHERE state_abbreviation = 'LA';
UPDATE locations SET state_name = 'MAINE' WHERE state_abbreviation = 'ME';
UPDATE locations SET state_name = 'MARYLAND' WHERE state_abbreviation = 'MD';
UPDATE locations SET state_name = 'MASSACHUSETTS' WHERE state_abbreviation = 'MA';
UPDATE locations SET state_name = 'MICHIGAN' WHERE state_abbreviation = 'MI';
UPDATE locations SET state_name = 'MINNESOTA' WHERE state_abbreviation = 'MN';
UPDATE locations SET state_name = 'MISSISSIPPI' WHERE state_abbreviation = 'MS';
UPDATE locations SET state_name = 'MISSOURI' WHERE state_abbreviation = 'MO';
UPDATE locations SET state_name = 'MONTANA' WHERE state_abbreviation = 'MT';
UPDATE locations SET state_name = 'NEBRASKA' WHERE state_abbreviation = 'NE';
UPDATE locations SET state_name = 'NEVADA' WHERE state_abbreviation = 'NV';
UPDATE locations SET state_name = 'NEW HAMPSHIRE' WHERE state_abbreviation = 'NH';
UPDATE locations SET state_name = 'NEW JERSEY' WHERE state_abbreviation = 'NJ';
UPDATE locations SET state_name = 'NEW MEXICO' WHERE state_abbreviation = 'NM';
UPDATE locations SET state_name = 'NEW YORK' WHERE state_abbreviation = 'NY';
UPDATE locations SET state_name = 'NORTH CAROLINA' WHERE state_abbreviation = 'NC';
UPDATE locations SET state_name = 'NORTH DAKOTA' WHERE state_abbreviation = 'ND';
UPDATE locations SET state_name = 'OHIO' WHERE state_abbreviation = 'OH';
UPDATE locations SET state_name = 'OKLAHOMA' WHERE state_abbreviation = 'OK';
UPDATE locations SET state_name = 'OREGON' WHERE state_abbreviation = 'OR';
UPDATE locations SET state_name = 'PENNSYLVANIA' WHERE state_abbreviation = 'PA';
UPDATE locations SET state_name = 'RHODE ISLAND' WHERE state_abbreviation = 'RI';
UPDATE locations SET state_name = 'SOUTH CAROLINA' WHERE state_abbreviation = 'SC';
UPDATE locations SET state_name = 'SOUTH DAKOTA' WHERE state_abbreviation = 'SD';
UPDATE locations SET state_name = 'TENNESSEE' WHERE state_abbreviation = 'TN';
UPDATE locations SET state_name = 'TEXAS' WHERE state_abbreviation = 'TX';
UPDATE locations SET state_name = 'UTAH' WHERE state_abbreviation = 'UT';
UPDATE locations SET state_name = 'VERMONT' WHERE state_abbreviation = 'VT';
UPDATE locations SET state_name = 'VIRGINIA' WHERE state_abbreviation = 'VA';
UPDATE locations SET state_name = 'WASHINGTON' WHERE state_abbreviation = 'WA';
UPDATE locations SET state_name = 'WEST VIRGINIA' WHERE state_abbreviation = 'WV';
UPDATE locations SET state_name = 'WISCONSIN' WHERE state_abbreviation = 'WI';
UPDATE locations SET state_name = 'WYOMING' WHERE state_abbreviation = 'WY';