-- RUN THIS SCRIPT SECOND



INSERT INTO countries(country_code, country_name)
VALUES 
('US', 'UNITED STATES'),
('CA', 'CANADA'),
('MX', 'MEXICO'),
('RU', 'RUSSIA'),
('CN', 'CHINA'),
('ZA', 'SOUTH AFRICA'),
('DE', 'GERMANY'),
('IT', 'ITALY'),
('ES', 'SPAIN'),
('PT', 'PORTUGAL'),
('FR', 'FRANCE'),
('DK', 'DENMARK'),
('SE', 'SWEDEN'),
('NO', 'NORWAY'),
('FI', 'FINLAND'),
('NL', 'NETHERLANDS'),
('BE', 'BELGIUM'),
('GR', 'GREECE'),
('RO', 'ROMANIA'),
('UA', 'UKRAINE'),
('PL', 'POLAND'),
('GB', 'UNITED KINGDOM'),
('GB', 'GREAT BRITAIN'),
('CH', 'SWITZERLAND'),
('AT', 'AUSTRIA'),
('HR', 'CROATIA'),
('BY', 'BELARUS'),
('CZ', 'CZECHIA'),
('IE', 'IRELAND'),
('IS', 'ICELAND'),
('HU', 'HUNGARY'),
('MT', 'MALTA'),
('LU', 'LUXEMBOURG'),
('SI', 'SLOVENIA'),
('RS', 'SERBIA'),
('CY', 'CYPRUS'),
('AL', 'ALBANIA'),
('LT', 'LITHUANIA'),
('MD', 'MOLDOVA'),
('MC', 'MONACO'),
('SK', 'SLOVAKIA'),
('EE', 'ESTONIA'),
('LI', 'LIECHTENSTEIN'),
('ME', 'MONTENEGRO'),
('SM', 'SAN MARINO'),
('LV', 'LATVIA'),
('BA', 'BOSNIA AND HERZEGOVINA'),
('AU', 'AUSTRALIA'),
('NZ', 'NEW ZEALAND');

INSERT INTO states(country_id, state_code, state_name)
VALUES 
('1', 'AL', 'ALABAMA'),
('1', 'AK', 'ALASKA'),
('1', 'AZ', 'ARIZONA'),
('1', 'AR', 'ARKANSAS'),
('1', 'CA', 'CALIFORNIA'),
('1', 'CO', 'COLORADO'),
('1', 'CT', 'CONNECTICUT'),
('1', 'DE', 'DELAWARE'),
('1', 'FL', 'FLORIDA'),
('1', 'GA', 'GEORGIA'),
('1', 'HI', 'HAWAII'),
('1', 'ID', 'IDAHO'),
('1', 'IL', 'ILLINOIS'),
('1', 'IN', 'INDIANA'),
('1', 'IA', 'IOWA'),
('1', 'KS', 'KANSAS'),
('1', 'KY', 'KENTUCKY'),
('1', 'LA', 'LOUISIANA'),
('1', 'ME', 'MAINE'),
('1', 'MD', 'MARYLAND'),
('1', 'MI', 'MICHIGAN'),
('1', 'MN', 'MINNESOTA'),
('1', 'MS', 'MISSISSIPPI'),
('1', 'MO', 'MISSOURI'),
('1', 'MT', 'MONTANA'),
('1', 'NE', 'NEBRASKA'),
('1', 'NV', 'NEVADA'),
('1', 'NH', 'NEW HAMPSHIRE'),
('1', 'NJ', 'NEW JERSEY'),
('1', 'NM', 'NEW MEXICO'),
('1', 'NY', 'NEW YORK'),
('1', 'NC', 'NORTH CAROLINA'),
('1', 'ND', 'NORTH DAKOTA'),
('1', 'OH', 'OHIO'),
('1', 'OK', 'OKLAHOMA'),
('1', 'OR', 'OREGON'),
('1', 'PA', 'PENNSYLVANIA'),
('1', 'RI', 'RHODE ISLAND'),
('1', 'SC', 'SOUTH CAROLINA'),
('1', 'SD', 'SOUTH DAKOTA'),
('1', 'TN', 'TENNESSEE'),
('1', 'TX', 'TEXAS'),
('1', 'UT', 'UTAH'),
('1', 'VT', 'VERMONT'),
('1', 'VA', 'VIRGINIA'),
('1', 'WA', 'WASHINGTON'),
('1', 'WV', 'WEST VIRGINIA'),
('1', 'WI', 'WISCONSIN'),
('1', 'WY', 'WYOMING');
